# values.yaml

replicaCount: 1

image:
  repository: docker.io/csibilevente14/vlm-chart-pattern-analyzer
  tag: 2025-10-25-2145
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "2"
    memory: "4Gi"
  limits:
    cpu: "4"
    memory: "8Gi"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: vlm.local
  path: /
  pathType: Prefix

nodeSelector: {}
tolerations: []
affinity: {}
