# Deployment Template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlm-infer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vlm-infer
  template:
    metadata:
      labels:
        app: vlm-infer
    spec:
      containers:
      - name: vlm-infer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
      nodeSelector: {{ toYaml .Values.nodeSelector }}
      tolerations: {{ toYaml .Values.tolerations }}
      affinity: {{ toYaml .Values.affinity }}
    
---

# Service Template
apiVersion: v1
kind: Service
metadata:
  name: vlm-infer
spec:
  selector:
    app: vlm-infer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}

---

# Ingress Template
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vlm-infer-ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: vlm-infer
            port:
              number: {{ .Values.service.port }}
{{- end }}
