name: Build and push Docker image

on:
  push:
    # branches: 
      # - master
    paths:
      - 'Dockerfile'
      - '*.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: vlm-chart-pattern-analyzer-runner
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start Docker service
        shell: powershell
        run: |
          Start-Process "C:\Program Files\Docker\Docker\Docker Desktop.exe"
          Start-Sleep -Seconds 20
          docker version

      - name: Verify Docker
        shell: cmd
        run: docker version

      - name: Log in to container registry
        shell: cmd
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Verify login
        shell: cmd
        run: docker info

      - name: Extract image tags
        shell: cmd
        id: tags
        run: |
          for /f "tokens=1-3 delims=/- " %%a in ("%date%") do set DATE=%%c%%a%%b
          for /f "tokens=1-2 delims=:." %%a in ("%time%") do set TIME=%%a%%b
          set DATETIME=%DATE%-%TIME%

          set repo=%REGISTRY%/%IMAGE_NAME%
          set branch=%GITHUB_REF_NAME%
          set sha=%GITHUB_SHA:~0,7%

          set tags=%repo%:%branch%-%DATETIME%,%repo%:%branch%-%sha%
          echo tags=%tags%>>%GITHUB_OUTPUT%
          echo first_tag=%repo%:%branch%-%DATETIME%>>%GITHUB_OUTPUT%

      - name: Build Docker image
        shell: cmd
        run: |
          for %%t in (%TAGS%) do (
            "C:\Program Files\Docker\Docker\resources\bin\docker.exe" build -t %%t .
          )

      - name: Push Docker image
        shell: cmd
        run: |
          for %%t in (%TAGS%) do (
            echo Pushing %%t...
            "C:\Program Files\Docker\Docker\resources\bin\docker.exe" push %%t
          )

      - name: Post build summary
        shell: cmd
        run: |
          echo Build complete: %FIRST_TAG%>>%GITHUB_STEP_SUMMARY%

