name: Build and push Docker image

on:
  push:
    # branches: 
    #   - master
    paths:
      - 'Dockerfile'
      - '*.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: vlm-chart-pattern-analyzer-runner
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start Docker service
        shell: powershell
        run: |
          Start-Process "C:\Program Files\Docker\Docker\Docker Desktop.exe"
          Start-Sleep -Seconds 20
          docker version

      - name: Verify Docker
        shell: cmd
        run: docker version

      - name: Log in to container registry
        shell: cmd
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Verify login
        shell: cmd
        run: docker info

      - name: Extract image tags
        shell: powershell
        id: tags
        run: |
          $datetime = Get-Date -Format "yyyyMMdd-HHmmss"
          $repo = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          $branch = "${{ github.ref_name }}" -replace '/','-'
          
          $tag = "${repo}:${branch}-${datetime}"
          
          echo "tags=${tag}" >> $env:GITHUB_OUTPUT
          echo "first_tag=${tag}" >> $env:GITHUB_OUTPUT
          
          Write-Host "Generated tag: ${tag}"

      - name: Verify build context
        shell: cmd
        run: |
          echo Current directory:
          cd
          echo.
          echo Directory contents:
          dir /B
          echo.
          if exist "src" (
            echo src directory exists
            dir src
          ) else (
            echo ERROR: src directory not found!
            exit /b 1
          )

      - name: Build Docker image
        shell: powershell
        timeout-minutes: 60
        run: |
          Write-Host "Building image: ${{ steps.tags.outputs.first_tag }}"
          docker build -t ${{ steps.tags.outputs.first_tag }} --progress=plain .
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Docker build failed with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }

      - name: Push Docker image
        shell: powershell
        timeout-minutes: 30
        run: |
          Write-Host "Pushing ${{ steps.tags.outputs.first_tag }}..."
          docker push ${{ steps.tags.outputs.first_tag }}
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Docker push failed with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }

      - name: Post build summary
        shell: cmd
        run: |
          echo Build complete: ${{ steps.tags.outputs.first_tag }}>>%GITHUB_STEP_SUMMARY%

