name: Build and push Docker image

on:
  push:
    branches: 
      - master
    paths:
      - 'Dockerfile'
      - '*.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: vlm-chart-pattern-analyzer-runner
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to container registry
        shell: pwsh
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | & "C:\Program Files\Docker\Docker\resources\bin\docker.exe" login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Extract image tags
        shell: pwsh
        id: tags
        run: |
          $repo = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}".ToLower()
          $branch = "${{ github.ref_name }}"
          $sha = "${{ github.sha }}".Substring(0,7)
          
          $tags = @(
            "${repo}:${branch}",
            "${repo}:${branch}-${sha}"
          )
          
          if ("${{ github.ref }}" -eq "refs/heads/master") {
            $tags += "${repo}:latest"
          }
          
          $tagString = $tags -join ","
          echo "tags=${tagString}" >> $env:GITHUB_OUTPUT
          echo "first_tag=$($tags[0])" >> $env:GITHUB_OUTPUT

      - name: Build Docker image
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $tags = "${{ steps.tags.outputs.tags }}" -split ","
          $buildArgs = @("build", ".")
          foreach ($tag in $tags) {
            $buildArgs += "-t"
            $buildArgs += $tag
          }
          & "C:\Program Files\Docker\Docker\resources\bin\docker.exe" $buildArgs
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

      - name: Push Docker image
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $tags = "${{ steps.tags.outputs.tags }}" -split ","
          foreach ($tag in $tags) {
            Write-Host "Pushing ${tag}..."
            & "C:\Program Files\Docker\Docker\resources\bin\docker.exe" push $tag
            if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          }

      - name: Post build summary
        shell: pwsh
        run: |
          $summary = @"
          ### Docker Build Summary
          
          **Image:** ``${{ steps.tags.outputs.first_tag }}``
          
          **All tags:**
          $("${{ steps.tags.outputs.tags }}" -split "," | ForEach-Object { "- ``$_``" } | Out-String)
          "@
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $summary
